<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8ZBAajb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8ZBAajb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8ZBAajb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8ZBAajb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8ZBAajb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8ZBAajb',
    'container.build_id' => '6dfc73ac',
    'container.build_time' => 1564505474,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8ZBAajb');
