<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSGnA32S\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSGnA32S/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSGnA32S.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSGnA32S\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSGnA32S\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SGnA32S',
    'container.build_id' => '60b33154',
    'container.build_time' => 1564476581,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSGnA32S');
