<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEGoLixD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEGoLixD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEGoLixD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEGoLixD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEGoLixD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EGoLixD',
    'container.build_id' => '4aa55a52',
    'container.build_time' => 1564415629,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEGoLixD');
